### ISSUE TITLE
Error resolving plugins.

### ISSUE THREAD

**Issue by mauvm** [mauvm/documark#1]
Compiling the [Documark example](https://github.com/mauvm/documark-example) gives the following error:

``` bash
Compiling..
Error!

/usr/local/lib/node_modules/documark/bin/documark-compile.js:39
    throw e;
          ^
Error: Cannot find module 'documark-theme-default'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at nextPlugin (/usr/local/lib/node_modules/documark/lib/Documark.js:152:14)
    at Documark.applyPlugins (/usr/local/lib/node_modules/documark/lib/Documark.js:161:3)
    at Stream.<anonymous> (/usr/local/lib/node_modules/documark/lib/Documark.js:197:9)
    at Stream.stream.write (/usr/local/lib/node_modules/documark/node_modules/event-stream/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:95:17)
```

This happens because Documark tries to resolve the package from its own location instead of the document root. I will have to rewrite it to take a [Grunt CLI](https://www.npmjs.com/package/grunt-cli) like approach.

**Comment by mauvm** [comment]
Fixed. Use the [documark-cli](https://github.com/mauvm/documark-cli) from now on.
