### ISSUE TITLE
What is minimum required version of wkhtmltopdf?

### ISSUE THREAD

**Issue by OrangeTux** [mauvm/documark#3]
By default version 0.9.9 of `wkhtmltopdf` is installed on Debian 7.8 (Wheezy). Compiling the sample project fails:

``` bash
$ documark compile
Compiling..
/home/auke/Downloads/documark-example/node_modules/documark/lib/Documark.js:214
                    throw new Error('Error generating PDF (code: ' +
                          ^
Error: Error generating PDF (code: Error: Unknown long argument --cache-dir

Name:
  wkhtmltopdf 0.9.9

Synopsis:, signal: undefined)!
    at /home/auke/Downloads/documark-example/node_modules/documark/lib/Documark.js:214:12
    at handleError (/home/auke/Downloads/documark-example/node_modules/documark/node_modules/wkhtmltopdf/index.js:70:7)
    at Socket.<anonymous> (/home/auke/Downloads/documark-example/node_modules/documark/node_modules/wkhtmltopdf/index.js:79:5)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

Installing [wkhtmltopdf 0.12.2.1](http://wkhtmltopdf.org/downloads.html) solved this issue for me. But iI think it should be stated somewhere which minimum version of `wkhtmltopdf` is required.

**Comment by mauvm** [comment]
You are absolute right! I have added version info to the README.

Also I'm working on a [wkhtmltopdf binary downloader](https://github.com/mauvm/wkhtmltopdf-downloader), that downloads the right version for you automagically. :)
